plugins {
    id 'groovy'
    id 'java-library'
    id 'maven-publish'
    alias(libs.plugins.javafx)
}

group = 'com.spidasoftware'
version = '1.0.6-SNAPSHOT'

repositories {
    mavenCentral()
}

java {
    toolchain {
        languageVersion = JavaLanguageVersion.of(21)
    }
    withSourcesJar()
    withJavadocJar()
}

dependencies {
    // versions are in libs.versions.toml
    api libs.groovy
    api libs.spring.context
    implementation libs.commons.lang3
    implementation libs.commons.beanutils
    implementation libs.slf4j.api
    testImplementation libs.spock.core
    testRuntimeOnly libs.logback.classic
    testRuntimeOnly libs.objenesis
    testRuntimeOnly libs.byte.buddy
    testRuntimeOnly libs.junit.platform.launcher
}

javafx {
    version = libs.versions.javafx.get()
    modules = [ 'javafx.controls', 'javafx.fxml' ]
    configuration = 'api'
}

tasks.named('test') {
    useJUnitPlatform()
}

publishing {
    publications {
        mavenJava(MavenPublication) {
            from components.java
        }
    }

    repositories {
        maven {
            url = providers.environmentVariable("ARTIFACTORY_URL_EXPOSED")
            credentials {
                username = providers.environmentVariable('ARTIFACTORY_USERNAME').orNull
                password = providers.environmentVariable('ARTIFACTORY_PASSWORD').orNull
            }
        }
    }
}
